## Generated by bindgen (ybus from the nim-windowing project)
## **DO NOT MODIFY THIS MANUALLY!**
import std/[options, tables]
import pkg/ybus/client/unix_sync, pkg/ybus/utils/wrapping

## Bindings for interface `org.freedesktop.Notifications`
proc notify*(
    client: unix_sync.BusClient,
    arg_0: string,
    arg_1: uint32,
    arg_2: string,
    arg_3: string,
    arg_4: string,
    arg_5: seq[string],
    arg_6: Table[string, Variant],
    arg_7: int32,
): Option[uint32] =
  let r: Option[Message] = client.call(
    path = "/org/freedesktop/Notifications",
    iface = "org.freedesktop.Notifications",
    destination = "org.freedesktop.Notifications",
    member = "Notify",
    arguments =
      @[
        wrap(arg_0),
        wrap(arg_1),
        wrap(arg_2),
        wrap(arg_3),
        wrap(arg_4),
        wrap(arg_5),
        wrap(arg_6),
        wrap(arg_7),
      ],
    signature = "susssasa{sv}i",
  )
  if r.isSome:
    let rv = r.get()

    return some(rv.body[0].u32)

proc closeNotification*(client: unix_sync.BusClient, arg_0: uint32) =
  discard client.call(
    path = "/org/freedesktop/Notifications",
    iface = "org.freedesktop.Notifications",
    destination = "org.freedesktop.Notifications",
    member = "CloseNotification",
    arguments = @[wrap(arg_0)],
    signature = "u",
  )

proc getCapabilities*(client: unix_sync.BusClient): Option[seq[string]] =
  let r: Option[Message] = client.call(
    path = "/org/freedesktop/Notifications",
    iface = "org.freedesktop.Notifications",
    destination = "org.freedesktop.Notifications",
    member = "GetCapabilities",
  )
  if r.isSome:
    let rv = r.get()

    var retvals = newSeqOfCap[string](rv.body.len)
    for elem in rv.body[0].elements:
      retvals &= elem.str
    return some(ensureMove(retvals))

proc getServerInformation*(client: unix_sync.BusClient): Option[seq[string]] =
  let r: Option[Message] = client.call(
    path = "/org/freedesktop/Notifications",
    iface = "org.freedesktop.Notifications",
    destination = "org.freedesktop.Notifications",
    member = "GetServerInformation",
  )
  if r.isSome:
    let rv = r.get()

    var retvals = newSeqOfCap[string](rv.body.len)
    for elem in rv.body:
      retvals &= elem.str
    return some(ensureMove(retvals))
